'''
Test Generator
'''

'''
将列表生成式中的中括号换成小括号就变成了一个生成器。
生成器是一个可迭代的对象，可以使用 for ... in 迭代
'''
print('=================Test generator generated by () =======================')
gen1 = (x * x for x in range(13))
print(gen1)

print(next(gen1))
print(next(gen1))
print('---------')

for xx in gen1:
    print(xx)

'''
使用yeid关键字的函数 定义生成式
'''
print('============Test generator generated by function yield ===============')

def create_gen2(nums):
    for i in range(nums):
        yield i*i*i
    return

gen2 = create_gen2(10)
for i in gen2:
    print(i)
